# src/SF/PlatformBundle/Resources/config/routing.yml

sf_platform_home:
    path:      /{page}
    defaults:
        _controller: SFPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*

sf_platform_view:
    path:      /advert/{advert_id}
    defaults: { _controller: SFPlatformBundle:Advert:view }
    requirements:
        id: \d+

# pourrait servir pour moteur de recherche
sf_platform_list:
  path: /list/{date}
  defaults:
    _controller: SFPlatformBundle:Advert:viewList

sf_platform_view_slug:
    path:      /{year}/{slug}.{_format}
    defaults:
        _controller: SFPlatformBundle:Advert:viewSlug
        format:      html
    requirements:
        year:   \d{4}
        format: html|xml

sf_platform_add:
    path:      /add
    defaults: { _controller: SFPlatformBundle:Advert:add }

sf_platform_edit:
    path:      /edit/{advert_id}
    defaults: { _controller: SFPlatformBundle:Advert:edit }
    requirements:
        id: \d+

sf_platform_delete:
    path:      /delete/{advert_id}
    defaults:
        _controller: SFPlatformBundle:Advert:delete
    requirements:
        id: \d+

sf_platform_purge:
    path:    /purge/{days}
    defaults:
        _controller: SFPlatformBundle:Advert:purge
    requirements:
        days: \d+
