services:
#    %locale%: le paramètre locale (pour récupérer la langue, définit dans le fichier app/config/parameters.yml) ;
#    @mailer: le service Mailer (pour envoyer des e-mails) ;
    sf_platform.antispam:
        class: SF\PlatformBundle\Antispam\SFAntispam
        arguments:
            - "@mailer"
            - '%locale%'
            - 50

parameters:
    mon_parametre: ma_valeur