services:
#    %locale%: le paramètre locale (pour récupérer la langue, définit dans le fichier app/config/parameters.yml) ;
#    @mailer: le service Mailer (pour envoyer des e-mails) ;
    sf_platform.antispam:
        class: SF\PlatformBundle\Antispam\SFAntispam
        arguments:
            - "@mailer"
            - '%locale%'
            - 50

    sf_platform.email.application_mailer:
        class: SF\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    sf_platform.doctrine_listener.application_creation:
        class: SF\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@sf_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }


parameters:
    mon_parametre: ma_valeur